### ISSUE TITLE
Not sure if permissions or something else

### ISSUE THREAD

**Issue by bsodcat** [BelkaDev/Spotify-Headless#5]
I've never messed with js so im not sure what I am missing, I figured it was an out of date puppeteer but it says its up to date.
I've also checked permissions, have you ran into this before?
After following along I get a error while typing the following command:

`$ node token.js`
```
(node:1124) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/anon/Spotify-Headless/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by BelkaDev** [comment]
Hi,  
It appears you're missing some dependencies, and you need to install the missing packages (assuming you're using a Debian-based distro)
`sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 lib`

**Comment by bsodcat** [comment]
Ah yup that was it, some of them were missing, beginner mistakes!
